onEvent('recipes', event => {
  //烹饪
  event.custom({       
  "type":"farmersdelight:cooking",  
  "experience":1.0,
  "cookingtime":200,
  "ingredients": [
    {
      "tag":"c:crops/cabbage"
    },
    {
      "tag":"c:dough"
    },
    {
      "tag":"c:raw_pork"
    }
  ],
  "result":{
    "item":"kubejs:pork_cabbage_boiled_dumpling",
    "count":2
  }
})
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:crops/tomato"
      },
      {
        "tag":"c:cooked_eggs"
      }
    ],
    "result":{
      "item":"kubejs:tomato_egg_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:crops/tomato"
      },
      {
        "tag":"c:raw_beef"
      }
    ],
    "result":{
      "item":"kubejs:beef_tomato_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "item":"minecraft:rabbit"
      }
    ],
    "result":{
      "item":"kubejs:rabbit_meat_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:raw_mutton"
      }
    ],
    "result":{
      "item":"kubejs:mutton_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:mushrooms"
      },
      {
        "tag":"raw_chicken"
      }
    ],
    "result":{
      "item":"kubejs:chicken_mushroom_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:mushrooms"
      }
    ],
    "result":{
      "item":"kubejs:mushroom_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:raw_fishes/cod"
      }
    ],
    "result":{
      "item":"kubejs:cod_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"c:raw_fishes/salmon"
      }
    ],
    "result":{
      "item":"kubejs:salmon_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "item":"minecraft:dandelion"
      }
    ],
    "result":{
      "item":"kubejs:dandelion_leaf_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "item":"minecraft:pufferfish"
      }
    ],
    "result":{
      "item":"kubejs:pufferfish_boiled_dumpling",
      "count":2
    }
  })
  event.custom({
    "type":"farmersdelight:cooking",
    "experience":1.0,
    "cookingtime":200,
    "ingredients": [
      {
        "tag":"c:crops/cabbage"
      },
      {
        "tag":"c:dough"
      },
      {
        "tag":"mca:babies"
      }
    ],
    "result":{
      "item":"kubejs:blame_meat_boiled_dumpling",
      "count":4
    }
  })
  //熔炼
  event.remove({input:'#mca:babies'})
  event.smelting('kubejs:blame_meat', '#mca:babies')
  event.campfireCooking('kubejs:blame_meat', '#mca:babies')
})

